### ISSUE TITLE
Header menu link "Proposals" opens a random ballot

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/app-telos-native#107]
**Describe the bug**
The header menu link "Proposals" opens a random ballot when first clicked.

**To Reproduce**
1. Load the site (home page)
2. Click on header menu link "Proposals"
3. It will open a random ballot

**Screenshots**
Note the current URL and the selection of header menu items. There's none selected.
![image](https://user-images.githubusercontent.com/4420760/191596447-c87ad9eb-e9cd-4637-966c-13ad5c197ca3.png)

After clicking the Proposal link, it gets selected and opens a random ballot
![image](https://user-images.githubusercontent.com/4420760/191598584-c85a4f39-8419-4f58-8a35-c6df63c299f9.png)

**Comment by karynemayer** [comment]
@Viterbo I've seen and was able to reproduce this behavior only needed an extra step:
- Open any proposal
- Close the proposal
- Click on Proposals link
- The Test 1 proposal appears

I was unable to reproduce it without opening and closing a proposal before

**Comment by Viterbo** [comment]
I close this issue because is fixed and merged

**Comment by Viterbo** [comment]
I reopen this issue since there was a [revert](https://github.com/telosnetwork/app-telos-native/pull/121) on the merging of the branch where this issue was solved.

**Comment by Viterbo** [comment]
Closing this issue because is fixed and merged
