### ISSUE TITLE
Improve buttons on the group cards for register vs already registered

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/app-telos-native#11]
We should also improve the UX around the treasuries, so it is more clear that a user needs to register or that they are already registered.

**Comment by karynemayer** [comment]
If we could add the number of voters from a group under the title of the group, that would be great.

![Image](https://user-images.githubusercontent.com/2939354/186205145-22e5311a-9491-44b3-a205-9628a4fb101b.png)
