### ISSUE TITLE
Proposals link is not highlighted when in the main page

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#116]
**Describe the bug**
Now that proposals are our main page, we should highlight Proposals in the header. It only highlights once we click and it redirect us to 'trails/ballots'.

**To Reproduce**

1. Go to the app telos
2. The proposals link in the main menu is not highlighted
3. Click on the link
4. Verify its the same page
5. See the link highlighted and your url has `trails/ballots`

**Expected behavior**
Highlight proposals in the header menu when we're in the home page
If possible, lets not use `trails/ballots` for the proposals anymore and keep only our home url 

**Screenshots**
![Image](https://user-images.githubusercontent.com/2939354/191862649-fe169d6c-ee7c-4d1d-b831-5579b998964a.png)

**Comment by karynemayer** [comment]
duplicate of #107

**Comment by Viterbo** [comment]
Closing this issue because is fixed and merged
