### ISSUE TITLE
Cancel Button for DAO registration without function

### ISSUE THREAD

**Issue by Kersten-TCD** [telosnetwork/app-telos-native#124]
The cancel button within the DAO/Group registration has no function.

1. Open App.telos.net
2. Login with your account
3. Open DAOs page
4. Select "Register as a voter" for any group
5. Click on "Cancel"
6. It is only possible to close the popup by refreshing the page

**Expected behavior**
Register popup should close when "Cancel" is selected.

![Bildschirmfoto 2022-09-23 um 14 57 35](https://user-images.githubusercontent.com/39388424/191966135-e3217d25-7760-43a9-b5e1-fdd65fdbbe0b.png)

**Comment by Viterbo** [comment]
Closing this issue because is duplicated as #112
