### ISSUE TITLE
Design better indication of if a user has voted and what a user has voted for

### ISSUE THREAD

**Issue by poplexity** [telosnetwork/app-telos-native#13]
When a user opens a ballot that they have voted on, we should indicate that they have already voted and auto-check which options they have voted for (they can re-vote still, which is ok).

This task should result in an approved design and the development task being created.

**Comment by karynemayer** [comment]
![Modal](https://user-images.githubusercontent.com/2939354/189019573-37f9e58d-d0ab-431a-b9a8-31ccb0598a8c.png)

**Comment by Viterbo** [comment]
This issue is duplicated in #150 which is already fixed in [5c25788](https://github.com/telosnetwork/app-telos-native/pull/148/commits/5c25788b1415036c0b7070288f5d8feed70ec131) and ready to be merged.
