### ISSUE TITLE
Improve error display

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#130]
**Is your feature request related to a problem? Please describe.**
It seems that the only way the user can read a relevant error message is by looking into the network response under dev tools. This means that the average user is simply unable to vote. Also, if we read the error message shown in the image, it looks like an app error, which is entirely misleading.

**Describe the solution you'd like**
We should strive to avoid errors. This is not always possible, so we should think of a better way to show the error messages so they are actionable to the users.

**Describe alternatives you've considered**
For common errors, as resource management, we should not only show the error from the response, but also indicate where the user can go to solve the problem.
For example, for a new user, we should say they lack ram to join the DAO and provide a link to where they can make the purchase. 

**Additional context**
The image below shows a new account trying to vote for the first time and pressing the `Join DAO` button.

<img width="1121" alt="Screen Shot 2022-09-23 at 15 23 17" src="https://user-images.githubusercontent.com/2939354/192064539-3320c98a-56b1-4d2f-b1ac-a92d9d1a822a.png">

**Comment by kylanhurt** [comment]
Strangely enough it seems like the error response from the nodes don't always have consistent structure. For example some errors I see have a `json` property in them:

![image](https://user-images.githubusercontent.com/6249205/193426730-fc671429-ce36-4c06-a489-126c3373a565.png)
