### ISSUE TITLE
Add token to metamask

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/app-telos-native#139]
Add icon/link for each token on coin list to add token to metamask wallet

**Comment by Viterbo** [comment]
I didn't get the idea. As long as I know, the token section of app-telos-native never had MetaMask tokens. In fact (again as far as I know) the whole site does not interact with MetaMask at all.

**Comment by donnyquixotic** [comment]
@karynemayer @DevArtemNuss @Viterbo , my mistake I initially added this to the wrong repo. disregard.

**Comment by karynemayer** [comment]
I'm closing this and creating a new one in teloscan project
