### ISSUE TITLE
Unify all the information regarding profile that would be required

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#140]
**Is your feature request related to a problem? Please describe.**
Currently, a profile is used in different projects and they are not necessarily the same. 
- [Telos Wallet](https://github.com/telosnetwork/telos-wallet)
- [ App Telos](https://github.com/telosnetwork/app-telos-native) - currently disabled
 
**Describe the solution you'd like**
- All data fields used in the profile for all repositories
- How the information is displayed
- How the information is saved and retained

**Additional context**
The output of this task should be a uniform list of fields

**Comment by Viterbo** [comment]
The fields in the smart contract `profiles` are:
- `account_name`: string
- `avatar`: string
- `bio`: string
- `display_name`: string
- `is_verified`: number
- `status`: string
