### ISSUE TITLE
Investigate how to improve showing proposals

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#145]
**Is your feature request related to a problem? Please describe.**
Right now, we rely on `get_table_rows` to get all the proposals information. Unfortunately, each call doesn't have a reliable quantity of data, i.e. we ask for 300 proposals and may or may not get the 300. 

**Describe the solution you'd like**
We want to be able to load all the proposals reliably.
Any optimization would be welcomed as well.

**Comment by Viterbo** [comment]
An attempt was made to address this problem in [7880e30](https://github.com/telosnetwork/app-telos-native/pull/148/commits/7880e308652a0c3a605310a4547e14311ee37c1b).
This may not be the definitive solution though.
