### ISSUE TITLE
Design new create ballot

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#146]
**Is your feature request related to a problem? Please describe.**
The creating ballot form is hard to use and not intuitive at all. Also, its tiny and everything is crowded.

**Describe the solution you'd like**
Design that uses the whole screen and helps the user to focus on creating their ballot.

#### Acceptance criteria
- The design should assume the user doesn't have previous knowledge of how polls work
- The design must work for mobile, tablet and desktop
- Design focused on polls ❓
- Reflect current naming (e.g. DAO instead of treasury)
- Indicate to the user how each voting type works 
- Indicate to the user how each DAO works
- Max and min options with explanation
- If the user is not in any DAO, display Join a DAO & create poll instead of Create Poll. This should have an explanation of why joining a DAO is required. 
- Add explanation for stake/liquid choices in ballot configuration when treasury allows a choice.
- Use another component to create options that look more friendly.

**Comment by Viterbo** [comment]
This issue is already aborded in #79, maybe we can rename the issue and continue with it

**Comment by karynemayer** [comment]
@poplexity should we only focus on `polls` for this form? We're not entirely sure.

**Comment by Viterbo** [comment]
I will suggest splitting the Ballot creation form into several steps using this wonderful component "Stepper"
https://quasar.dev/vue-components/stepper

1 - Ballot main info
- Title
- Description
- Image URL (with preview)
- file.pdf

2 - DAO selection
- (x) Telos community    ( ) Custom DAO
- "information about the selected option"
- If Custom DAO is selected then show
  - list of current registered DAOs for user
  - Button "Join new DAO" to redirect the user to DAOs section
  - Vote with: ( ) Liquid tokens    ( ) Staked token    (x) Both

3 - Voting options
- (x) Simple Yes or No    ( ) Yes/No/Abstain    ( ) Multiple option
- "information about the selected option"
- if any of the first two are selected, then show two or three fields to edit the default words
- if the Multiple Options is selected, then show an editable item list like a simple TODO-list app:
  - intput for the displayable text of the new option
  - "add" button
  - list of already created items with a cross button to delete it from the list
  - button: "clear list" 
  - checkbox: [x] "Voters can only choose one option"
  - if the user unchecks it, then we show:
    - "information about 'min' n 'max' fields"
    - input "Min"
    - input "max"

4 - Open Voting
- checkbox: [x] "Open voting right away"
- if user keep option checked then show
  - input: "Ending date" 

5 - Finish
- show preview with the info
- alert about the cost in TLOS
- Button "Confirm"

**Comment by Viterbo** [comment]
There's a video for the current approach:
https://github.com/telosnetwork/app-telos-native/pull/188
