### ISSUE TITLE
ballots should be ordered by ending time by default

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/app-telos-native#149]

**Comment by Viterbo** [comment]
fixed in [b7a0b26](https://github.com/telosnetwork/app-telos-native/pull/148/commits/b7a0b26e1f2fcfec7c55f433596b0df5891147b4)

**Comment by karynemayer** [comment]
@Viterbo, I don't think this should apply to the active ones. Those should show the ones that are about to end first, so the user doesn't have to scroll down to be able to vote on a proposal at the last minute.

I've created issue #157
