### ISSUE TITLE
Create button pattern

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#159]
**Is your feature request related to a problem? Please describe.**
The current vote button will only show that it's disabled by the pointer indicator, which will not be valuable for the smartphone user without a pointer. This is one example of a broader problem: lack of design and consistency.

For this task, we should use the most we can from [Quasar Button](https://v1.quasar.dev/vue-components/button).

**Describe the solution you'd like**
For this story, we should define and apply a consistent behavior for the buttons and their several states. From this task, the following definitions:
- Look and feel of primary, secondary and tertiary buttons.
- Transition between states.
- For each button type (e.g. primary) define the states active, hover, focused and disabled.

The newly designed component should be adopted throughout the website to promote consistency.

**Definitions**
Looking into the current apps with a white background, we should use `#571AFF` as the primary color for the buttons.
- Primary: standard button with `#571AFF` as background
- Secondary: outline button with `#571AFF` as color (including border) and background (change opacity for the hover and click)
- Tertiary: flat button with `#571AFF` as color and hover/click (with lower opacity)

**Comment by Kersten-TCD** [comment]
@karynemayer these are the brand guidelines and color definitions from the telos.net website. These were also considered for the initial designs of OBE and should be helpful.

[styleguide.pdf](https://github.com/telosnetwork/app-telos-native/files/9677892/styleguide.pdf)
