### ISSUE TITLE
Investigate current state of unit testing

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#160]
### Why
We don't have any automated tests right now, and this is a considerable risk, especially when we work on new features.

### Acceptance criteria
- Identify if Jest is already setup in the project.
- Setup Jest for unit test if its not already setup
- Create unit tests for one component - the simplest one
- Add the running of unit tests to CI

**Comment by DevArtemNuss** [comment]
Now we can implement unit-tests (Jest) to our project.
Depend on our version Quasar, our project cant support Jest tests.

![Image](https://user-images.githubusercontent.com/92740446/194085803-b6c37ce0-17eb-4485-a083-a01f7c70bc84.png)

**Comment by karynemayer** [comment]
We won't address this in this repository
https://github.com/telosnetwork/epics/issues/9
