### ISSUE TITLE
Identify steps that allow users to vote on custom DAOs

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#183]
## Overview

A list of requirements to be able to vote in a ballot from a custom DAO. We also want to know where we can execute the actions in the current state of things, like if there is a website/interface that we can use for it.

## Acceptance criteria

- List of requirements for voting
- List of UIs that allow the users to execute one or more steps, if it already exists.
- New issues created to reflect the necessary fixes

## Tasks

- [ ] Identify the necessary steps to be able acquire 
- [ ] Task 2

**Comment by Viterbo** [comment]
#207 is part of the solution for this
