### ISSUE TITLE
Interface for editing a treasury

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#189]
## Overview

Allow treasury managers to be able to configure the token to be transferable and stakeable, if desired.

## Acceptance criteria

The treasury manager should be able to edit the treasury:
- [ ] Set the tokens as transferable
- [ ] Set the treasury as stakeable

**Comment by karynemayer** [comment]
@poplexity Viter has investigated the smart contract and has identified that it is possible to edit a treasury later. We're wondering if a treasury that doesn't have the token as transferable has any value. If it doesn't, we should set the token as transferable when creating the treasury.

**Comment by Viterbo** [comment]
This is addressed in the issue #207

**Comment by Viterbo** [comment]
This is being addressed in issue #207
so I close this one
