### ISSUE TITLE
Enable linter rules that can be automatically fixed

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#190]
## Overview

The goal of this issue is to run all the rules that can be **automatically** fixed by running `lint --fix`.
The rules should follow https://github.com/telosnetwork/teloscan/issues/127

## Acceptance criteria

- Identify the rules that are automatically fixed from https://github.com/telosnetwork/teloscan/issues/127
- Run the fix
- Open the PR
- Create issues for the ones that can't be automatically fixed from https://github.com/telosnetwork/teloscan/issues/127

## Tasks

- [ ] [Default linting rules](https://github.com/telosnetwork/teloscan/issues/127) are applied
- [ ] #216 is merged
- [ ] All issues have been created

**Comment by donnyquixotic** [comment]
@karynemayer this is resolved by #164

**Comment by donnyquixotic** [comment]
@karynemayer PR #161 fixes the linter enabling `lint --fix`. I'll leave this open to potentially update rules if necessary.
