### ISSUE TITLE
Bug - 'Take me to my profile' on new account creation

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/app-telos-native#204]
## Overview

On successful creation of a new account there is a button 'Take me to my profile' that doesn't do anything

## Steps to reproduce

1. Create a new Telos account
3. See the Congratulations modal
4. Click the `Take to my profile` button

![image](https://user-images.githubusercontent.com/6848910/197608064-54009268-1704-4f1f-8112-dc7ab62a8b4c.png)

## Current behavior

Nothing happens

## Expected behavior

- The button text is changed to `Sign in`
- The button signs the user on his new account
- The button redirects the user to the main page (the proposals list)

**Comment by karynemayer** [comment]
@donnyquixotic I like the suggestion to repurpose the button more because it gives feedback to the user that their account has been successfully created and nudges them to their next step: signing in
