### ISSUE TITLE
Proposals that are not started show ended in 1969

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#222]
## Overview

Proposals that haven't started yet show as if they ended at the start of Unix epoch time, which means the date is set as 0. This information looks quite misleading.

<img width="1273" alt="Screen Shot 2022-11-03 at 15 43 18" src="https://user-images.githubusercontent.com/2939354/199849228-8713eb93-a045-4576-9202-4e4b56b7bbb1.png">

## Steps to reproduce

1. Go to the main page
2. Remove `active` and add `not started` in the status filtering

## Current behavior

As showed in the screenshot, see `Proposal ended December 31st 1969` for all proposals

## Expected behavior

In order to not mislead people, if the proposal end time is 0, we should show `To be defined` instead

**Comment by Viterbo** [comment]
This issue was addressed in issue #205 and was merged in this [PR#215](https://github.com/telosnetwork/app-telos-native/pull/215) already merged.

So I close this issue.

## Screenshots

![Image](https://user-images.githubusercontent.com/4420760/201237213-29a82b13-1062-4035-88ca-5126ac0979ed.png)
