### ISSUE TITLE
Allow again to skip immediately open new ballots for voting

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/app-telos-native#226]
# Description
All needed features to have not opened ballots are already in place, so we can open the possibility to have new ballots without immediately opening for voting.

![image](https://user-images.githubusercontent.com/4420760/200602552-080e5447-d511-4065-b514-0d54bbf6fc70.png)

**Comment by karynemayer** [comment]
@Viterbo I've upgraded this to urgent so we prioritize it
