### ISSUE TITLE
displaying user profiles fails when the user is not logged

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/app-telos-native#234]
# Description
The user profile page displays correctly when the user is logged in, but it fails when the user is not.

## how to reproduce
1 - access the site [app.telos.net](https://app.telos.net/ ) and log out
2 - access this link to [my profie page](https://app.telos.net/profiles/display/viterbotelos) 
3 - See how it fails to load and shoy my profile data
4 - Now loggin as viterbotelos@active using cleos-authenticator
5 - access again this link to [my profie page](https://app.telos.net/profiles/display/viterbotelos) 
6 - how it works perfectly

| logged | not logged |
|----------|-----------------|
|![image](https://user-images.githubusercontent.com/4420760/201421692-ed1d78d0-579b-4b21-a82a-9dc3ee4e6f83.png)|![image](https://user-images.githubusercontent.com/4420760/201421707-cd959fa1-b305-4e0d-9986-d6110bf216dd.png)|

**Comment by karynemayer** [comment]
We won't address this at this point
https://github.com/telosnetwork/epics/issues/9
