### ISSUE TITLE
Make testnet faucet page more efficient by adding input validation

### ISSUE THREAD

**Issue by sakibarifin** [telosnetwork/app-telos-native#259]
Telos testnet faucet page is inefficient. When content with wrong format is inputted, the page allows the user to submit them. This process is time consuming. Instead, the button should be disabled until the user enters the content in correct format.

![Telos Testnet](https://user-images.githubusercontent.com/33556544/214757375-b35a1a86-f6c5-498a-bf7e-045ade0fd56b.png)

**Comment by thatzprem** [comment]
Testnet Faucet URL: https://app.telos.net/testnet/developers

**Comment by donnyquixotic** [comment]
This page is already in being redesigned here: https://github.com/telosnetwork/app-telos-native/pull/335

**Comment by Viterbo** [comment]
Done in [this PR](https://github.com/telosnetwork/app-telos-native/pull/335)
