### ISSUE TITLE
Linter - force alias/prevent relative paths on imports

### ISSUE THREAD

**Issue by donnyquixotic** [telosnetwork/app-telos-native#28]
## Overview

In order to improve the code base, we've been adding linter rules to be enforced so we have a more consistent code. 

## Acceptance criteria

- add linter rule to force use of alias/prevent relative paths
- refactor all files to replace relative import paths with alias (`~/file`  instead of `../../file`)

**Comment by karynemayer** [comment]
This won't be addressed in this repository
https://github.com/telosnetwork/epics/issues/9
