### ISSUE TITLE
Need to Know Where to Put Arbitration / Resolve Links in Navigation Bar

### ISSUE THREAD

**Issue by kylanhurt** [telosnetwork/app-telos-native#58]
**Is your feature request related to a problem? Please describe.**
Not sure where I can put the links in the navbar for the upcoming arbitration portal

**Describe the solution you'd like**
Either add a navigation bar item for "Resolve" or create a new navbar item that is a dropdown where additional modules can include links

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/6249205/189206593-c80f713b-ac07-4ddd-8cbf-0924df52ebac.png">

**Comment by karynemayer** [comment]
@kylanhurt do you have your own login or would you be using the one provided by telos app?
