### ISSUE TITLE
Can't properly filter ballots by type

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#66]
**Describe the bug**
By default, the filters have `active` and `VOTE` selected. If you change the type to `proposal`, it will only show the proposals from that list, but the same doesn't happen with `poll`. When selecting the `poll` type, the list is empty even though there is one item at the list. 

**To Reproduce**
1. Go to ballots
2. See that the listed ballots (with `active` and `VOTE`) contain one poll (/ballots/rbqs4bmmel2w/1663123846224)
3. Scroll up
4. Add the type filtering with `poll` selected
5. There are no ballots returned

**Expected behavior**
The ballot of type poll that is active and belongs to the VOTE treasury should appear.

**Comment by Kersten-TCD** [comment]
@karynemayer Default filter settings for all governance types are not showing any results. It seems that Status "active" does not match any meta data of active proposals.

![Bildschirmfoto 2022-09-15 um 15 47 22](https://user-images.githubusercontent.com/39388424/190420659-99a33080-a052-41dd-9fcf-de63dc2a1697.png)

![Bildschirmfoto 2022-09-15 um 15 47 15](https://user-images.githubusercontent.com/39388424/190420702-68bc1c0c-40b2-46d6-8496-bbfc4dd7942f.png)

**Comment by karynemayer** [comment]
@Kersten-TCD @DevArtemNuss 
The acceptance criteria for this task remain to be able to filter the proposals and polls using the type. For the `active` filtering not working, we have created #75
