### ISSUE TITLE
Infinite scroll requires scroll to show first results

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#67]
**Describe the bug**
When reaching the ballots page, you can see the three dots indicating a request is being made, and it stops after a few seconds. If you don't scroll down on the page, the ballots don't show.

**To Reproduce**
1. Go to the ballots page
2. Don't click on anything or scroll
3. See the three dots being animated
4. See the three dots disappearing
5. No ballot is shown

**Expected behavior**
Active ballots from the VOTE treasury should be listed

**Screenshots**
<img width="921" alt="Screen Shot 2022-09-13 at 20 09 06" src="https://user-images.githubusercontent.com/2939354/190049657-73de992e-cd74-4eac-b11c-cb252fc061ac.png">

**Comment by Viterbo** [comment]
fixed in this commit [543dd05](https://github.com/telosnetwork/app-telos-native/pull/72/commits/543dd05d3ccd0262d7058d4337056306ecb6a091).
