### ISSUE TITLE
[Epic] Token overview and creation 

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#74]
# Why
The main functionalities are not working correctly, but a discussion on the value of this feature is still required.

**Comment by Viterbo** [comment]
## Current situation 
In fact, the main functionalities (at least in the front end) were fixed and merged with this [PR 59](https://github.com/telosnetwork/app-telos-native/Pull/59)

The problem with this whole section is that it is considered without value (although it seems different to me).

## What do I propose to do?
In my opinion, these are some changes that can be done to put this section again in production:
- Register button for everyone to join for free with an existing token.
- Categorize the tokens in three levels of trust:
  - **whitelisted** (trusted)
  - **registered** (default value)
  - **banned** (not trusted but not canceled either)
- Use Telos Decide ballots to change the trusted lever for every token individually.

Of course, most of the new functionalities require modifying the smart contract as well.

## Why do I consider this important?
Imagine someone who wants to create a system for every token to participate (like a DEX or a Defi system). It is desirable that all tokens participating are real and not scams o broken tokens.

This requires the system creator to also create a solution for that and be constantly updating the token list.

If we centralize this solution everyone can just ask if the token is trusted from within any smart contract to let or prohibit any new token to join the particular system.

**Comment by karynemayer** [comment]
All information has been moved to [Tokens milestone](https://github.com/telosnetwork/app-telos-native/milestone/12)
