### ISSUE TITLE
Active filtering needs to be reviewed

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#75]
**Is your feature request related to a problem? Please describe.**
We need to investigate the `active` filtering since there may not be reliable metadata that we can use it.

**Describe the solution you'd like**
We want to see all active ballots when the `active` filter is selected.

**Describe alternatives you've considered**
Filter the ballots by the end date being later than the current date.

**Comment by DevArtemNuss** [comment]
Hi i have PR for this too )

**Comment by karynemayer** [comment]
@DevArtemNuss This task relates to the `active` filter specifically. I understand that your PR solves a possible issue where the `active` proposals don't seem to exist because they're not showing.

This task, however, is an investigation of how the current `active` filter is working vs how it should be working. We suspect we will need to rely on the end date to identify active proposals.

**Comment by karynemayer** [comment]
fixed by #96
