### ISSUE TITLE
Update the menu to reflect current functionalities

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#76]
**Is your feature request related to a problem? Please describe.**
Right now, we have several links in the top menu that are not needed or lead to broken features.
In order to make the voting process smother - which is the current main value app telos delivers - we would like to remove them. That way, we eliminate non-working stuff from the vision of the user and allow them to focus on their task.  

**Describe the solution you'd like**
- Remove Contacts link from top menu
- Remove Tokens link from top menu
- Remove sub groups from Decide
- Rename Decide to Proposals
- Rename Groups to DAOs

**Comment by Viterbo** [comment]
I close this issue because is fixed and merged.
