### ISSUE TITLE
Develop the ballot creation re-design

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#79]
**Is your feature request related to a problem? Please describe.**
To enable users to create their proposals smother, we want to design a form that leads them on the right path to it. Right now, we're not completely sure what a proposal should have as information and what is acceptable or not beyond what the smart contract allows. 

**Describe the solution you'd like**
Implementation following what has been accepted by #146 
- Unit tests should be added to all related components

**Comment by Viterbo** [comment]
After a meeting with @poplexity we get to the following list if features / changes to make for the ballot creation form:

- [ ] A responsive design (portrait for mobile and wider for desktop)
- [ ] remove category field. For now, only Polls are allowed.
- [ ] Rename treasury field to DAO (to be consistent with the new header links)
- [ ] Display information about the current field being edited when necessary:
  - [ ] Voting Method. How does work every option.
  - [ ] Treasury (now DAO) what does mean changing the DAO
  - [ ] Max and Min Options. Explain what they mean.
- [ ] If the user selects a DAO on which is not registered, a button to join the DAO should appear right afterward.
- [ ] Remove the current Options field and replace it with something more friendly
- [ ] The creation of the final content field should follow [DCMS-V2 Specification](https://github.com/telosnetwork/telos-decide/blob/master/dcms-v2.md)
