### ISSUE TITLE
Ballots page does not start querying data until the user scrolls.

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/app-telos-native#83]

**Comment by karynemayer** [comment]
@Viterbo I think this is a duplicate of #67 (being addressed at #72 )

**Comment by Viterbo** [comment]
@karynemayer In deed. I created this issue and branch to solve this problem and then realise what you just said. So I merged the solution to the branch bug/fix-infinity-scrool-init0pos in the commit [543dd05](https://github.com/telosnetwork/app-telos-native/pull/72/commits/543dd05d3ccd0262d7058d4337056306ecb6a091). 

So when you merge that PR https://github.com/telosnetwork/app-telos-native/pull/72 this fix will be included

**Comment by Viterbo** [comment]
I'm going to close this issue because it is duplicated.
Follow #67 instead.
