### ISSUE TITLE
Make entering a group a seamless experience to the user

### ISSUE THREAD

**Issue by Viterbo** [telosnetwork/app-telos-native#92]

**Comment by Viterbo** [comment]
mini tasks:
- [ ] does already exist a variable with logged user DAO registration info? if not, create it.
- [ ] when a ballot opens, if the info about user being registered is not present then fetch it.
- [ ] If the user is not registered
  - [ ] if the DAO access is not public create a button to redirect the user to the DAO's page (this is a temporal solution for a quick fix)
  - [ ] else change the button text "Join DAO & Vote"
  - [ ] and add the registration action to the button transaction.
- [ ] else, the user is already registered so leave everything as it is now.

**Comment by Viterbo** [comment]
Im going to pause this development for several reasons:
- although telos.decide::regvoter is correctly added to the transaction list of actions, it fails with the message "cannot vote for fewer than min options" which is generated [here](https://github.com/telosnetwork/telos-decide/blob/master/contracts/decide/src/voter.cpp#L162) in the smart contract. So it needs a deeper look.
- I found several other bugs that make difficult the testing of these new features. So I will fix those other bugs first and then come back to this issue and finish it.

**Comment by karynemayer** [comment]
I'm closing this issue.
The problem of entering a group to vote is already solved, even if it requires one additional click. 

Further improvement is addressed here #131
