### ISSUE TITLE
Create elections page

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/app-telos-native#94]
**Is your feature request related to a problem? Please describe.**
We want to have a different page for showing the elections. This is the first part of it: creating the page with the current design.

**Describe the solution you'd like**
- A copy of the current ballots page
- The page only shows the elections (already removed from the ballots page)
- The filter doesn't allow filter by `type`
- There is an `Elections` link on the top menu

**Describe alternatives you've considered**
A simplified version of the filter should be displayed. This filter should be the same component, but a variant that doesn't show the type filter.

**Comment by Viterbo** [comment]
Closing this issue because is fixed and merged
